- include: pacman.yml
  when: ansible_distribution == "Archlinux"

- include: sudoers.yml
  when: ansible_distribution == "Archlinux"

- include: yaourt.yml
  when: ansible_distribution == "Archlinux"
