### mirrorlist.pacnew file management
- stat: path=/etc/pacman.d/mirrorlist.pacnew
  register: mirrorlistPacnew

- command: /usr/bin/env sed -i -r '/## {{country}}/,/^$/ s/^#(Server)/\1/' /etc/pacman.d/mirrorlist.pacnew
  when: mirrorlistPacnew.stat.exists

- copy: src=/etc/pacman.d/mirrorlist.pacnew dest=/etc/pacman.d/mirrorlist remote_src=true
  when: mirrorlistPacnew.stat.exists

- file: path=/etc/pacman.d/mirrorlist.pacnew state=absent

### multilib
- shell: /usr/bin/env grep "^\[multilib\]" /etc/pacman.conf
  register: multilib_activated
  changed_when: multilib_activated.rc != 0
  failed_when: false
  check_mode: no

- shell: /usr/bin/env sed -i '/^#*\[multilib\]/,/^$/ s/^#//' /etc/pacman.conf
  notify: pacman update
  when: multilib_activated.rc != 0

### cache refreshing. Only when cache older than 1 week (7*24*60*60 seconds)
- stat: path=/var/lib/pacman/sync/extra.db
  register: oldCacheFound

- pacman: update_cache=yes
  when: oldCacheFound.stat.mtime|int < (ansible_date_time.epoch|int - 604800)

### pkgfile 
- pacman: name=pkgfile

- shell: pkgfile --update

### installation of packages
- pacman: name={{item}} state=present
  with_items: "{{base_packages}}"
