# Creation of the ansibleme (default, changed by user variable) user, used for instalation purpose
- user: name={{user}} group=users

- pacman: name=sudo

- file:
    path: /home/{{user}}/Tmp
    state: directory
    mode: 0750
    owner: "{{user}}"
    group: users

- file:
    path: /home/{{user}}/.gnupg
    state: directory
    mode: 0700
    owner: "{{user}}"
    group: users

- copy:
    src: gnupg/gpg.conf
    dest: /home/{{user}}/.gnupg/gpg.conf
    owner: "{{user}}"
    group: users
    mode: 0700

- template:
    src: etc/sudoers.d/user
    dest: /etc/sudoers.d/{{user}}
    owner: root
    group: root
    mode: 0640

